name: Bug report
description: Report something that is broken or not working as expected
title: "[Bug]: "
labels: ["backend"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Describe the bug clearly.
      placeholder: "When I ..., the app ..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      placeholder: "I expected ..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "OS, browser, branch, commit hash..."
