name: Feature request
description: Suggest an improvement or a new feature
title: "[Feature]: "
labels: ["frontend"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this solve?
      placeholder: "As a user, I want ..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: "We could add ..."
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: false
