name: Bug report
description: Report a reproducible bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug clearly.
      placeholder: Steps, expected vs actual...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide steps to reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened.
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "e.g. 3.11.9"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / tracebacks
      description: Paste any relevant logs. Avoid secrets.
      render: shell
    validations:
      required: false
